service: c-code-review

provider:
  name: aws # Where to host
  runtime: python3.11
  region: ap-southeast-1
  environment:
    STAGE: prod

functions:
  api:
    handler: main.handler # From where Mangum runs in your code
    events:
      - httpApi: '*'

custom:
  pythonRequirements:
    dockerizePip: true     # Ensures Linux-compatible packages for Lambda
    useStaticCache: false
    invalidateCache: true # To avoid running the existing package and start new
    slim: true             # Remove unnecessary files from packages
    # manyLinux: true # Avoids Rust compilation and forces use of manyLinux wheels
    # cacheDir: "./.serverless-cache" # Store in project local
    # pipCmdExtraArgs:
    #   - "--only-binary=tree-sitter-language-pack"
    # environment:
    #   RUSTUP_HOME: /root/.cache/puccinialin
    #   CARGO_HOME: /root/.cache/puccinialin/cargo
    #   PATH: /root/.cache/puccinialin/cargo/bin:$PATH
    noDeploy:
      - boto3              # Already provided by Lambda runtime
      - botocore
      - awscli
      - uvicorn

package:
  exclude:
    - tests/**
    - docs/**
    - .git/**
    - __pycache__/**
    - "**/__pycache/**"
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - .vscode/**
    - local_config/**      # Any local-only files
    - .venv/**
    - .env
    - Procfile