service: c-code-review

provider:
  name: aws # Where to host
  runtime: python3.11
  region: ap-southeast-1
  environment:
    STAGE: prod
    UPSTASH_REDIS_REST_URL: ${env:UPSTASH_REDIS_REST_URL}
    UPSTASH_REDIS_REST_TOKEN: ${env:UPSTASH_REDIS_REST_TOKEN}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN, ''}
    GITHUB_APP_ID: ${env:GITHUB_APP_ID, ''}
    GITHUB_PRIVATE_KEY: ${env:GITHUB_PRIVATE_KEY, ''}
    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET, ''}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY, ''}

plugins:
  - serverless-dotenv-plugin

# layers: # This is to have two lambda functions share code
#   sharedCode:
#     path: layer
#     compatibleRuntimes:
#       - python3.11

functions:
  api:
    handler: main.handler # From where Mangum runs in your code
    timeout: 30
    memorySize: 512
    # layers:
    #   - { Ref: SharedCodeLambdaLayer }
    events:
      - httpApi: '*'

# //  worker:
# //    handler: worker.lambda_handler # Other lambda handler to run background jobs
# //    layers:
# //      - { Ref: SharedCodeLambdaLayer }
# //    events:
# //      - sqs: # SQS queue where the background jobs will be pushed
# //          arn: arn:aws:sqs:us-east-1:123456789012:PRJobQueue

custom:
  pythonRequirements:
    dockerizePip: true     # Ensures Linux-compatible packages for Lambda
    useStaticCache: false
    invalidateCache: true # To avoid running the existing package and start new
    slim: true             # Remove unnecessary files from packages
    # manyLinux: true # Avoids Rust compilation and forces use of manyLinux wheels
    # cacheDir: "./.serverless-cache" # Store in project local
    # pipCmdExtraArgs:
    #   - "--only-binary=tree-sitter-language-pack"
    # environment:
    #   RUSTUP_HOME: /root/.cache/puccinialin
    #   CARGO_HOME: /root/.cache/puccinialin/cargo
    #   PATH: /root/.cache/puccinialin/cargo/bin:$PATH
    noDeploy:
      - boto3              # Already provided by Lambda runtime
      - botocore
      - awscli
      - uvicorn

package:
  exclude:
    - tests/**
    - docs/**
    - .git/**
    - __pycache__/**
    - "**/__pycache/**"
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - .vscode/**
    - local_config/**      # Any local-only files
    - .venv/**
    - .env
    - Procfile
    - layer/
